name:                rsa
version:             0.1.0.0
github:              "ambiso/rsa"
license:             MIT
author:              "ambiso"
maintainer:          "ambiso@invalid"
copyright:           "2018 ambiso"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ambiso/rsa#readme>

dependencies:
- base >= 4.7 && < 5
- mtl ^>= 2.2
- arithmoi ^>= 0.6
- random ^>= 1.1

library:
  source-dirs: src

executables:
  rsa-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rsa

tests:
  rsa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rsa
